/**
 * Starlight Theme Plugin: @knowledge-forge-ai/starlight-theme-terminal-nova
 * Generated by @knowledge-forge-ai/theme-forge-stellar-loom
 */

export default function themePlugin(options = {}) {
  return {
    name: "@knowledge-forge-ai/starlight-theme-terminal-nova",
    hooks: {
      "config:setup"({ config, updateConfig, logger }) {
        const existingCustomCss = Array.isArray(config.customCss) ? config.customCss : [];
        const themeCssPath = "@knowledge-forge-ai/starlight-theme-terminal-nova/styles/theme.css";

        // Cascade order: theme stylesheet defaults first, consumer custom CSS second
        const customCss = existingCustomCss.includes(themeCssPath)
          ? [...existingCustomCss]
          : [themeCssPath, ...existingCustomCss];

        const existingComponents = config.components ? { ...config.components } : {};
        if (existingComponents.PageTitle) {
          logger?.info?.(`[@knowledge-forge-ai/starlight-theme-terminal-nova] Preserving existing consumer PageTitle component override`);
        } else {
          existingComponents.PageTitle = "@knowledge-forge-ai/starlight-theme-terminal-nova/components/PageTitleFrame.astro";
        }
        updateConfig({
          customCss,
          components: existingComponents,
        });
      },
    },
  };
}
